[project]
name = "proyecto2-data"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "ayalaSL", email = "iris@softlogic.com" }
]
requires-python = ">=3.11"
dependencies = [
    "ipykernel>=7.3.0",
    "jupyter>=1.1.1",
    "matplotlib>=3.11.1",
    "numpy>=2.4.6",
    "pandas>=3.0.5",
    "seaborn>=0.13.2",
]

[project.scripts]
proyecto2-data = "proyecto2_data:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"
